### PR TITLE
Add some useful seed migrations and position importer for GPE 

### PR DESCRIPTION
**Pull request by courtenay**
..and scope requests to the GPE position IDs which are all 500 and above.

WIP

### CODE REVIEW

**Comment by thedaniel** [comment]
i guess we should also seed it with slots, but that can be in a separate PR - this worked for me with

```bash
composer install
php artisan migrate:fresh --seed
```

**Comment by courtenay** [comment]
This is the migration related to https://github.com/gpe-tech/ranger-clubhouse-web/issues/14

You'll need to run `composer install` to update your php cache for this new php files.

**Comment by courtenay** [comment]
you can make a single slot and then 'copy 24', but yes a migration would be better agree

**Comment by courtenay** [comment]
let's make a shift slot generator then merge this for everyone else!

**Comment by thedaniel** [comment]
ah yes, everyone else - if you don't get to this in the next 12 hours or so I'll pick it up in my ❇️ day off work ❇️ tomorrow

**Comment by thedaniel** [comment]
I added a really dumb seeder that adds an 8 hour gate crew shift for a a week from `last monday`. we could always improve it later

**Pull request merged**
